site_name: Destrix
site_description: Destrix is a developer-focused admin system on Roblox, making it easier for developers who want a flexible and non-disruptive admin/moderation system in their game, for free.
site_url: https://docs.destrix.app
repo_url: https://github.com/DestrixApp
repo_name: DestrixApp

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
        auto_title: false
        linenums: true
        anchor_linenums: true
    - pymdownx.keys
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - abbr
    - attr_list
    - pymdownx.snippets

nav:
  - index.md
  - Getting Started:
    - Installation Guide: /Getting_Started
  - Commands:
    - Commands/index.md
    # Utility
    - Utility:
      - /ban: Commands/specifics/ban.md
      - /server-ban: Commands/specifics/sban.md
      - /temp-ban: Commands/specifics/tban.md
      # - /pban: Commands/specifics/pban.md
      - /kick: Commands/specifics/kick.md
      - /server-lock: Commands/specifics/serverlock.md
      - /shutdown: Commands/specifics/shutdown.md
      - /force-shutdown: Commands/specifics/fshutdown.md
      # - /tslock: Commands/specifics/serverlock.md
      - /reload-map: Commands/specifics/reloadmap.md
      - /countdown: Commands/specifics/countdown.md
      - /timer: Commands/specifics/timer.md
      - /message: Commands/specifics/message.md
      - /hint: Commands/specifics/hint.md
      - /spectate: Commands/specifics/view.md
      - /prompt-gamepass: Commands/specifics/prompt-gamepass.md
      - /prompt-asset: Commands/specifics/prompt-asset.md
      - /logs: Commands/specifics/logs.md
      - /rank: Commands/specifics/rank.md
      - /temp-rank: Commands/specifics/temp-rank.md
      - /force-place: Commands/specifics/fplace.md

    # Software
    - Software:
      - /about: Commands/specifics/about.md
      - /check-plus: Commands/specifics/checkplus.md
      - /check-rank: Commands/specifics/checkrank.md
      - /ping: Commands/specifics/ping.md
      - /prefix: Commands/specifics/prefix.md
      - /gametime: Commands/specifics/gametime.md
      - /dversion: Commands/specifics/dversion.md
      - /plus: Commands/specifics/plus.md
      - /commands: Commands/specifics/commands.md
      - /bans: Commands/specifics/bans.md
      - /plus: Commands/specifics/plus.md
      - /credits: Commands/specifics/credits.md
    
     # Contact
    - Contact:
      - /modcall: Commands/specifics/modcall.md

    # Fun
    - Fun:
      - /fire: Commands/specifics/fire.md
      - /sit: Commands/specifics/sit.md
      - /mars: Commands/specifics/mars.md
      - /jupiter: Commands/specifics/jupiter.md
      - /brazil: Commands/specifics/brazil.md
      - /freeze: Commands/specifics/freeze.md
      - /stratosphere: Commands/specifics/stratosphere.md
      - /rocket: Commands/specifics/rocket.md
  - DAX:
    - About: /DAX/about
    - Introduction:
      - DisableEXEType: /DAX/Introduction/disabling-commands
    - API Reference:
      - Command Types: /DAX/Reference/CommandTypes
      - Functions:
        - DisableEXEType: /DAX/Reference/Functions/DisableEXEType
        - FireCommand: /DAX/Reference/Functions/FireCommand
  - DAXI: /DAXI/about
  - Extenstions: /Extenstions
  - Features: /Features

extra:
  homepage: /
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://destrix.app/t/github
      name: Destrix on Github
    - icon: fontawesome/brands/twitter
      link: https://destrix.app/t/twitter
      name: Destrix on Twitter
    - icon: fontawesome/brands/discord
      link: https://destrix.app/t/discord
      name: Destrix on Discord
    - icon: fontawesome/brands/trello
      link: https://destrix.app/t/trello
      name: Destrix on Trello
    - icon: fontawesome/brands/youtube
      link: https://destrix.app/t/youtube
      name: Destrix on YouTube
    - icon: destrix/patreon-2023
      link: https://destrix.app/t/patreon
      name: Wolfite on Patreon
    - icon: destrix/logo
      link: https://destrix.app/
      name: Destrix.app
  alternate:
    - name: English
      link: https://docs.destrix.app/
      lang: en
    # - name: Español
    #   link: /es/
    #   lang: es
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      - reject
    cookies:
      analytics: Analytics
  analytics:
    provider: google
    property: G-3PNP6MZLFT
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
            Anything we can improve? Tell us on our <a href="//destrix.app/feedback/docs/" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/thumb-down
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="//destrix.app/?feedback=docs" target="_blank" rel="noopener">feedback form</a>.
copyright: >
  Copyright &copy; 2022 - 2024 <a href="//wolfite.dev?to=twitter">@Wolfite_</a>
  <br><a href="#__consent">Change cookie settings</a>
plugins:
  # - material/social
  - search:
      lang: en
# tags plugin seems to be removing the search tool somehow.

extra_css:
    - stylesheets/extra.css

theme:
  name: material
  logo: https://cdn.discordapp.com/attachments/786817739867947009/1164107525692592179/destrix-anim-docs.gif?ex=6542029e&is=652f8d9e&hm=038b2bd9942d2507f16d69bc1e7d371e34ba11b89e15c32e6804a8eed58af5dd&
  favicon: https://docs.destrix.app/favicon.ico
  language: en
  custom_dir: overrides

  

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.view
    - content.tooltips
    - content.code.annotate
    - navigation.footer
    - content.tabs.link
    - search.suggest
    - search.share
    - announce.dismiss
    - toc.follow
    - navigation.indexes
    # - toc.integrate
  icon:
    repo: fontawesome/brands/github

  
  
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      # scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode