site_name: Destrix
site_description: Destrix is a developer-focused admin system on Roblox, making it easier for developers who want a flexible and non-disruptive admin/moderation system in their game, for free.
site_url: https://docs.destrix.app
repo_url: https://github.com/DestrixApp
repo_name: Destrix
edit_uri: https://github.com/DestrixApp/docs/blob/main/docs/
docs_dir: "docs"
# view_uri: /docs/docs/docs
extra_javascript:
  - js/extra.js

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
        auto_title: false
        linenums: true
        # anchor_linenums: true
    - pymdownx.keys
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - abbr
    - md_in_html
    - attr_list
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - footnotes
    - toc:
       permalink: true
       title: On this page

nav:
  - index.md
  - Getting Started:
    # - Getting_Started/index.md
    - getting-started/index.md
    - Configurations: getting-started/configurations.md
    - Advanced: getting-started/advanced.md
    - Changelog:
      - getting-started/changelog/index.md
      - What's Next?: getting-started/changelog/whats-next.md
  - Commands:
    - commands/index.md
    - Parameters: commands/parameters.md
    - Custom Commands: commands/custom-commands.md

    # Utility
    - Utility:
      - /ban: commands/specifics/ban.md
      - /server-ban: commands/specifics/sban.md
      - /temp-ban: commands/specifics/tban.md
      # - /pban: Commands/specifics/pban.md
      - /kick: commands/specifics/kick.md
      - /server-lock: commands/specifics/server-lock.md
      - /shutdown: commands/specifics/shutdown.md
      - /force-shutdown: commands/specifics/fshutdown.md
      # - /tslock: Commands/specifics/serverlock.md
      - /viewpl: commands/specifics/viewpl.md
      - /reload-map: commands/specifics/reloadmap.md
      - /countdown: commands/specifics/countdown.md
      - /change: commands/specifics/change.md
      - /timer: commands/specifics/timer.md
      - /message: commands/specifics/message.md
      - /hint: commands/specifics/hint.md
      - /spectate: commands/specifics/view.md
      - /inspect-avatar: commands/specifics/inspect-avatar.md
      - /prompt-gamepass: commands/specifics/prompt-gamepass.md
      - /prompt-asset: commands/specifics/prompt-asset.md
      - /logs: commands/specifics/logs.md
      - /rank: commands/specifics/rank.md
      - /temp-rank: commands/specifics/temp-rank.md
      - /force-place: commands/specifics/fplace.md
      - /reset: commands/specifics/reset.md
      - /poll: commands/specifics/poll.md
      - /connection-logs: commands/specifics/connection-logs.md

    # Software
    - Software:
      - /about: commands/specifics/about.md
      - /check-plus: commands/specifics/check-plus.md
      - /check-rank: commands/specifics/check-rank.md
      - /ping: commands/specifics/ping.md
      - /prefix: commands/specifics/prefix.md
      - /game-time: commands/specifics/game-time.md
      - /elapsed-time: commands/specifics/elapsed-time.md
      - /place-name: commands/specifics/placename.md
      - /ranks: commands/specifics/ranks.md
      - /dversion: commands/specifics/dversion.md
      - /commands: commands/specifics/commands.md
      - /changelog: commands/specifics/changelog.md
      - /bans: commands/specifics/bans.md
      - /limits: commands/specifics/limits.md
      - /plus: commands/specifics/plus.md
      - /credits: commands/specifics/credits.md
      - /hide-ui: commands/specifics/hideui.md
      - /show-ui: commands/specifics/showui.md
      - /randomn: commands/specifics/randomn.md
      - /preview-filter: commands/specifics/preview-filter.md
    
     # Contact
    - Contact:
      - /modcall: commands/specifics/modcall.md

    # Fun
    - Fun:
      - /fire: commands/specifics/fire.md
      - /sit: commands/specifics/sit.md
      - /mars: commands/specifics/mars.md
      - /jupiter: commands/specifics/jupiter.md
      - /brazil: commands/specifics/brazil.md
      - /freeze: commands/specifics/freeze.md
      - /stratosphere: commands/specifics/stratosphere.md
      - /rocket: commands/specifics/rocket.md
      - /blur: commands/specifics/blur.md
      - /glitch: commands/specifics/glitch.md
      - /fling: commands/specifics/fling.md
      - /bighead: commands/specifics/bighead.md
      - /paint: commands/specifics/paint.md

    # Standard
    - Standard:
      - /fly: commands/specifics/fly.md
      - /kill: commands/specifics/kill.md
      - /loopkill: commands/specifics/loopkill.md
      - /explode: commands/specifics/explode.md
      - /heal: commands/specifics/heal.md
      - Optional:
        - /rejoin: commands/specifics/rejoin.md
        - /follow: commands/specifics/follow.md

      # Cosmetic
    - Cosmetic:
      - /smoke: commands/specifics/smoke.md
      - /sparke: commands/specifics/sparkle.md
      - /glow: commands/specifics/glow.md
      - /glass: commands/specifics/glass.md
      - /gold: commands/specifics/gold.md
    
      # Customization
    - Customization:
      - /change-bloom: commands/specifics/change-bloom.md

      # Developer
    - Developer:
      - /change-camera-type: commands/specifics/change-camera-type.md
      - /devconsole: commands/specifics/devconsole.md
    
    - Misc:
      # - Categories: Commands/categories.md
      - Rules: commands/rules.md
  - DAX:
    - About: DAX/v1/about.md
    - Introduction:
      - Interfacing: DAX/v1/Introduction/interfacing-with-the-panel.md
      # - DisableEXEType: DAX/v1/Introduction/disabling-commands.md
    - API Reference:
      - Command Types: DAX/v1/Reference/CommandTypes.md
      - Functions:
        - DisableEXEType: DAX/v1/Reference/Functions/DisableEXEType.md
        - FireCommand: DAX/v1/Reference/Functions/FireCommand.md
        - TogglePanel: DAX/v1/Reference/Functions/TogglePanel.md
  - DAXI: 
    - About: DAXI/v1/about.md
    - Introduction:
      - Interfacing: DAXI/v1/intro/interfacing.md
    - API Reference:
      - Functions:
        - DeclareIntegration: DAXI/v1/reference/functions/DesclareIntegration.md
        - DestrixIntegration:DeclareCommand: DAXI/v1/reference/functions/DestrixIntegration:CreateCommand.md
  - Extensions: 
    - Extensions/index.md
    - Security Policy: Extensions/extensions-security-policy.md
    - Manifest V1: Extensions/manifest/v1.md
    - Endorsed Extensions: Extensions/endorsed-extensions.md
    - Additional Structure: Extensions/structure.md
    - Plugins:
      - Get Started: Extensions/Plugins/Getting_Started.md
    - Themes:
      - Extensions/Themes/Creating/index.md
      - Get Started: Extensions/Themes/Creating/index.md
      - Guidelines: Extensions/Themes/Creating/Guidelines.md
  - Plus:
    - plus/index.md
    - Benefits: plus/benefits.md
    - Enterprise:
      - plus/enterprise/index.md
  # - Features: Features/feature.md
  - News:
    - news/index.md

extra:
  homepage: /
  tags:
    DAX: DAX
    Commands: Commands
    Plus: Plus
    Utility: Utility
    Moderation: Moderation
    Software: Software
    Fun: Fun
    Standard: Standard
    Contact: Contact
    Cosmetic: Cosmetic
    Customization: Customization
    Developer: Developer
    Extensions: Extensions
    Themes: Themes
    Plugins: Plugins
    Security: Security
    Hidden: Hidden
    Dangerous: Dangerous
    Destrix: Destrix
    Outdated: Outdated
    Archive: Archive
    Security: Security
    SSecurity: Security
    Reference: Reference
  status:
    new: Recently added
    deprecated: Deprecated
    plus: Plus
    beta: Beta
    enterprise: Plus Enterprise
  social:
    - icon: fontawesome/brands/github
      link: https://destrix.app/t/github
      name: Destrix on Github
    - icon: fontawesome/brands/twitter
      link: https://destrix.app/t/twitter
      name: Destrix on Twitter
    - icon: fontawesome/brands/discord
      link: https://destrix.app/t/discord
      name: Destrix on Discord
    - icon: fontawesome/brands/trello
      link: https://destrix.app/t/trello
      name: Destrix on Trello
    - icon: fontawesome/brands/youtube
      link: https://destrix.app/t/youtube
      name: Destrix on YouTube
    - icon: destrix/patreon-2023
      link: https://destrix.app/t/patreon
      name: Wolfite on Patreon
    - icon: bootstrap/chat-dots-fill
      link: https://forum.destrix.app
      name: Destrix Forum
    # - icon: destrix/logo
    #   link: https://destrix.app/
    #   name: Destrix.app
  alternate:
    - name: English
      link: https://docs.destrix.app/
      lang: en
    # - name: Español
    #   link: https://es.docs.destrix.app/?from=lang_en
    #   lang: es
    # - name: 日本語
    #   link: https://jp.docs.destrix.app/?from=lang_en
    #   lang: jp
    - name: Help us add languages!
      link: https://destrix.app/?t=discord
      lang: jp
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      - reject
    cookies:
      analytics: Analytics (Google)
      
  analytics:
    provider: google
    property: G-3PNP6MZLFT
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
            Anything we can improve? Tell us on our <a href="//destrix.app/feedback/docs/" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/thumb-down
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="//destrix.app/?feedback=docs" target="_blank" rel="noopener">feedback form</a>.
copyright: >
  Copyright &copy; 2022 - 2024 <a href="//wolfite.dev?to=twitter">@Wolfite_</a>
  <br><a href="#__consent">Change cookie settings</a>
  <br><a href="?plus">Destrix Plus</a>&nbsp;&nbsp;&nbsp;<a href="?plus-billing">Billing</a>
  <br>&nbsp;
plugins:
  # - material/social
  - search:
      lang: en
  - blog:
      blog_dir: news
      blog_toc: true
      categories_toc: false
      pagination_per_page: 10
      draft_if_future_date: true
      post_dir: "{blog}/articles"
      authors_file: "{blog}/.authors.yml"
      authors: true
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "view/{date}/{slug}"
      categories_sort_by: !!python/name:material.plugins.blog.view_post_count
      authors_profiles: true
      authors_profiles_name: Authors
      authors_profiles_url_format: "a/{slug}"
      authors_profiles_toc: true
      # categories_allowed:
      #   - Destrix
      # authors_file: "{blog}/.authors.yml"
  - tags
      # tags_file: misc/tags.md
  - git-committers:
      repository: DestrixApp/docs
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - meta
# tags plugin seems to be removing the search tool somehow.
# EDIT 13/11/23: This seems to be fixed now.

extra_css:
    - stylesheets/extra.css

theme:
  name: material
  logo: https://cdn.discordapp.com/attachments/786817739867947009/1164107525692592179/destrix-anim-docs.gif?ex=6542029e&is=652f8d9e&hm=038b2bd9942d2507f16d69bc1e7d371e34ba11b89e15c32e6804a8eed58af5dd&
  favicon: https://docs.destrix.app/favicon.ico
  language: en
  custom_dir: overrides

  

  features:
    - navigation.tabs
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.view
    # - content.tabs.link
    - content.code.select
    - content.tooltips
    - content.code.annotate
    - navigation.footer
    - content.tabs.link
    - search.suggest
    - search.share
    - announce.dismiss
    - toc.follow
    - navigation.indexes
    # - toc.integrate
  icon:
    repo: destrix/logo
    annotation: material/plus-circle
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/fire-flame-curved
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: material/lightning-bolt-circle
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    tag:
      DAX: fontawesome/solid/plug
      Commands: material/chat
      Utility: material/lightbulb
      Moderation: material/block-helper
      Software: material/cog
      Contact: fontawesome/solid/phone
      Fun: fontawesome/solid/fire-flame-curved
      Standard: material/calendar
      Cosmetic: octicons/sparkle-fill-16
      Customization: fontawesome/solid/palette
      Dangerous: material/lightning-bolt-circle
      Plus: bootstrap/plus-circle-dotted
      Outdated: material/eye-off
      Archive: material/archive
      Security: material/security
      SSecurity: material/server-security
      Reference: material/book

  
  
  palette:

    - media: "(prefers-color-scheme)"
      primary: blue
      accent: blue
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to system preference




















































### Example Configuration ###

# Custom Homepage Elements
home_cover_image: https://docs.destrix.app/cdn/logo.png # This path starts at your root mkdocs directory.
home_cover_image_black: https://docs.destrix.app/cdn/logo-black.png # This path starts at your root mkdocs directory.
home_tagline: Destrix
home_description: |
  Destrix is the ultimate admin and moderation companion, specifically crafted with developers in mind.

# Gradient Color
home_gradient_hsla: hsl(231.43, 14.89%, 9.22%) # Default Green: hsla(160deg,47%,55%,1)

# Custom Homepage Button(s)
home_button1_name: Get Started                  # Comment this parameter out to remove the button.
home_button1_url: getting-started/                       # This path starts at your root mkdocs directory.
home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"
home_button1_icon: people                        # Options: "people", "gear", "image"
home_button1_blurb: |                            # Short description of this button / section.
  The step-by-step installation guide for the Destrix admin system. Follow these simple steps to easily integrate Destrix into your Roblox game, unlocking a world of efficiency, flexibility, and power.


home_button2_name: Commands   # Comment this parameter out to remove the button.
home_button2_url: Commands/    # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button2_icon: gear       # Options: "people", "gear", "image"
home_button2_blurb: |         # Short description of this button / section.
  Destrix has a lot of new and exciting commands, this is a large list of what those commands are and what they do, by category.

home_button3_name: DAX   # Comment this parameter out to remove the button.
home_button3_url: DAX/v1/about    # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button3_icon: image      # Options: "people", "gear", "image"
home_button3_blurb: |         # Short description of this button / section.
  The Destrix API Module, abbreviated as DAX (or DAXM), is a specialized module designed to facilitate effortless server-side interaction and control over Destrix for scripts.

home_button4_name: Extensions   # Comment this parameter out to remove the button.
home_button4_url: Extensions/    # This path starts at your root mkdocs directory.
home_button4_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button4_icon: custom      # Options: "people", "gear", "image"
home_button4_blurb: |         # Short description of this button / section.
  Make Destrix the way you want it to look, or add some more features with Destrix Extensions. A complete guide on how to install themes and plugins or make your own.

home_button5_name: DAXI   # Comment this parameter out to remove the button.
home_button5_url: DAXI/    # This path starts at your root mkdocs directory.
home_button5_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button5_icon: custom      # Options: "people", "gear", "image"
home_button5_blurb: |         # Short description of this button / section.
  Integrate Destrix with your models or plugins and start making commands that work seemlessly with Destrix in any experience with your own custom code and input.

home_button6_name: Plus   # Comment this parameter out to remove the button.
home_button6_url: plus/    # This path starts at your root mkdocs directory.
home_button6_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button6_icon: custom      # Options: "people", "gear", "image"
home_button6_blurb: |         # Short description of this button / section.
  Whether your a player or a developer — plus has you covered — level up your game in every game Destrix is in. With new commands and early access all for a cheap price.

home_button_news_name: News   # Comment this parameter out to remove the button.
home_button_news_url: blog/    # This path starts at your root mkdocs directory.
home_button_news_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button_news_icon: custom      # Options: "people", "gear", "image"
home_button_news_blurb: |         # Short description of this button / section.
  Stay up to date with Destrix, learn of upcoming changes, updates, and what to expect.

# Homepage Code Execution
home_execute_js: | # Javascript to execute when accessing the homepage
  console.log("This is an example!");

