site_name: Destrix

theme:
  name: material
  logo: /cdn/logo.png
  favicon: /favicon.ico
  language: en
  custom_dir: overrides
  copyright: Copyright &copy; 2023 - 2023 Wolfite
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate

  markdown_extensions:
  - pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny #material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night #material/brightness-4
        name: Switch to light mode

  extra:
    homepage: /
    # generator: false
    social:
    - icon: fontawesome/brands/twitter
      link: https://destrix.app/t/twitter
      name: Destrix on Twitter
    version:
      default: stable
      provider: wolfite