authors:
  wlft:
    name: Wolfite
    description: Creator
    avatar: https://github.com/wlft.png
  vrsion:
    name: Ver
    description: Random
    avatar: https://tr.rbxcdn.com/3f0688a282b0620b92d01b21a412055e/150/150/Avatar/Png